### ISSUE TITLE
Investigate missing text for some users

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/ainow#43]
Had one report of the text not rendering at all on Linux with Chrome.

Unable to reproduce so far, but will keep looking into it

**Comment by wrightmartin** [comment]
Possibly related https://github.com/google/fonts/issues/10

**Comment by wrightmartin** [comment]
We can serve this from Mozilla's CDN it fixes it, need to investigate if we can just request the styles we require (normal, normal italic, bold)

**Comment by hazelesque** [comment]
You mentioned in IRC that, whilst the Mozilla version of Fira Sans fixes this issue, the download from Mozilla's CDN was ~8 times larger due to the Mozilla version not using unicode-range subsets.

It occurred to me that Typekit might have Fira Sans... and it turns out[0] that it does!

Does our Adobe Creative Cloud subscription include Typekit? Apparently "A Portfolio plan is included with most Creative Cloud subscriptions"[1]. It would appear that TypeKit also supports[2][3] subsetting.

If it does, it seems like it might be worth a shot?

[0] https://typekit.com/fonts/fira-sans
[1] https://typekit.com/plans
[2] http://blog.typekit.com/2015/01/13/launched-and-live-custom-language-subsetting-options/
[3] https://helpx.adobe.com/typekit/using/language-support-subsetting.html

**Comment by wrightmartin** [comment]
@hazelesque This was what I was going to check this morning, but you beat me to it! 

We do have typekit - I'll switch them over. Thanks for doing the hard work on this one 👍

**Comment by hazelesque** [comment]
@wrightmartin you're welcome, glad I could help! :)

**Comment by wrightmartin** [comment]
@hazelesque this is now live on the staging site, do you want to give it a test? http://ainow.staging.mysociety.org/

**Comment by hazelesque** [comment]
@wrightmartin this seems to be working for me now, although I seem to get a brief "Flash of Unstyled Text" - the text appears with the page load, then changes size/shape a fraction of a second later, and reflows - which is a little jarring.

Do you get that when viewing the page in Chrome? (It does it on F5/Ctrl+R for me too, as well as the initial page load.)

Reading about this subject[0], it seems that there are various trade-offs here, between rendering with the fallback font briefly, rendering with no text briefly, or rendering with just the Roman variant of the text (forcing the browser to fake any bold and italic until that loads).

I guess that's your call.

P.S. I checked, and it looks like TypeKit does[1] generate base64-encoded data:// URI font-face declarations, so I guess it isn't a delay between the @font-face declaration and actually downloading the font, hrm :/

[0] https://css-tricks.com/fout-foit-foft/
[1] http://sosweetcreative.com/2613/font-face-and-base64-data-uri

**Comment by wrightmartin** [comment]
@hazelesque yeah - previously we've left out the ```async``` option on the typekit text, but it makes typekit's JS block page render, so it can result in a blank page if there's a network problem between the client and typekit's servers, even if ainow's website is fine. 

Generally I'd choose speed over style every time - but we can always revisit this is the FOUT is too pronounced
